# Site
repository: sam42996/resume-theme
favicon: images/pfp_crop.png

# Content configuration version
version: 2

# Personal info
name: Sam Griffin-Ortiz
title: Aspiring Dev/Future Tech Support
email: samgomusic@gmail.com
website: www.sam42996.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  sam42996
# youtube_username: 

# About Section
# about_title: About Me
about_profile_image: images/pfp_crop.png
about_content: |- # this will include new lines to allow paragraphs
  Hi, my name is Sam. I am an interdisciplinary creative with an interest in technology, music, and networked art.
 
  I'm currently in the process of upgrading my coding skills in NodeJS and Rust. 

  I am most skilled in:  
            <mark>Creative problem solving</mark> and 
            <mark>troubleshooting</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:  
      - layout: top-middle
        title: On Air Warning 

           <p><iframe width="560" height="315" src="https://www.youtube.com/embed/QTzBLETHacY" title="OAW Video" frameborder="0" allowfullscreen=""> </iframe> </p>

        quote: 
          An explainer video for On Air Warning. Check out the rest of the channel for more detailed tutorials.
        description: | # this will include new lines to allow paragraphs
          On Air Warning is a 3-light video conference indicator born out of the Work From Home boom of 2020. I have performed a variety of roles as assistant to the CEO, including handling the motion graphics, voiceover, original music, and video editing for the tutorials on OAW's [YouTube channel](https://www.youtube.com/c/OnAirWarning). Check out one of many examples above, and feel free to peruse the product [website](https://onairwarning.com) 

      - layout: top-middle
        title: Audio Programming in Max/MSP 

          <p><iframe width="560" height="315" src="https://www.youtube.com/embed/bmqW2p5Z6j4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen> </iframe> </p>

        quote: 
          A example of my abilities programming in Max/MSP.
        description: | # this will include new lines to allow paragraphs
          [Max/MSP](http://cycling74.com) is a visual programming language designed for audiovisual artists. Like many people of a similar ilk, I discovered my interest in coding with the help of Max's friendly layout and detailed documentation. While I've done all of my work in this field as a hobbyist, my immersion in it has strenthened my ability to think in modular terms, which I find gives me an advantage in learning new programming languages efficiently. Feel free to clone [the repo](https://github.com/sam42996/Clown-FX) and try out the program yourself. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Reed College
        caption: 2016-2020
        sub_title: BA in Music
        quote: >
          Reed is a small-ish liberal arts college in Portland, Oregon with rigorous academics and a spirit of open-mindedness. 
        description: | # this will include new lines to allow paragraphs
          My time at Reed was marked by significant growth and transformation. I went in thinking I'd be a Theatre or French major. I ultimately majored in Music. In the process of studying electronic music, I discovered my interest in technology more broadly. This snowballed into a desire to work with computers, which is the reason you're reading this right now. :) 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in programming and video art some of my other interests and hobbies are:
      - Meditation
      - Literature
      - Generative AI Art


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-cayman
